version: 24.04
os: ubuntu
files:
  - source: /
    destination: /home/ubuntu/python-test
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: /install-dependencies
      runas: root
  AfterInstall:
    - location: /after-install
      runas: root
